### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by CPScript** [hankypoo7old1/ISUathletics#1]
# remake this repo "the-blooket-hacks", no one can stop you from uploading software to github... you didn't have to delete the scripts in the repo

**Comment by hankypoo7** [comment]
> # remake this repo "the-blooket-hacks", no one can stop you from uploading software to github... you didn't have to delete the scripts in the repoye
you know what, yeah your right im gonna start on that

**Comment by CPScript** [comment]
i just did lol

**Comment by CPScript** [comment]
also, go back to your old account... this new one sucks lol
